channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - seaborn
  - ipykernel
  - contextily
  - manim
  - scikit-learn
  - python-dotenv
  - omegaconf
